// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonAccounting: typeof import('~icons/carbon/accounting')['default']
    CarbonArrow: typeof import('~icons/carbon/arrow')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonCr: typeof import('~icons/carbon/cr')['default']
    CarbonCross: typeof import('~icons/carbon/cross')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonDoor: typeof import('~icons/carbon/door')['default']
    CarbonEn: typeof import('~icons/carbon/en')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLo: typeof import('~icons/carbon/lo')['default']
    CarbonLog: typeof import('~icons/carbon/log')['default']
    CarbonLogin: typeof import('~icons/carbon/login')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogout: typeof import('~icons/carbon/logout')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonRegister: typeof import('~icons/carbon/register')['default']
    CarbonS: typeof import('~icons/carbon/s')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    CarbonSi: typeof import('~icons/carbon/si')['default']
    CarbonSign: typeof import('~icons/carbon/sign')['default']
    CarbonSignin: typeof import('~icons/carbon/signin')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonT: typeof import('~icons/carbon/t')['default']
    CarbonTo: typeof import('~icons/carbon/to')['default']
    CarbonTogg: typeof import('~icons/carbon/togg')['default']
    CarbonToggle: typeof import('~icons/carbon/toggle')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CarbonWro: typeof import('~icons/carbon/wro')['default']
    CarbonWrong: typeof import('~icons/carbon/wrong')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Login: typeof import('./pages/Login.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SidebarLink: typeof import('./components/SidebarLink.vue')['default']
  }
}

export { }
